# stage 1 build
FROM node:18 AS builder 

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . . 

RUN yarn build

# Stage 2 production
FROM node:18-alpine 

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app ./

EXPOSE 3000

CMD ["yarn", "start"]
