name: Deploy Docker Image to ECR

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    name: Build and Push to Amazon ECR
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1  

    - name: Build, tag, and push image to Amazon ECR
      working-directory: ./app
      env:
        AWS_ECR_REGISTRY: 977098994448.dkr.ecr.eu-west-2.amazonaws.com 
        # AWS_ECR_REPOSITORY: threat-model-project

      run: |
        docker build -t $AWS_ECR_REGISTRY/threat-model-project ./app
        docker tag threat-model-app $AWS_ECR_REGISTRY/threat-model-project
        docker push $AWS_ECR_REGISTRY/threat-model-project

    - name: Clean up post build
      run: docker rmi $AWS_ECR_REGISTRY/AWS_ECR_REPOSITORY

