name: provision terraform infrastructure 

on:
  workflow_dispatch: 
    
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: eu-west-2
          

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version:  1.9.8


    - name: Execute terraform init
      run: terraform init
      working-directory: ./terraform

    - name: Execute terraform validate
      run: terraform validate
      working-directory: ./terraform

    - name: Execute terraform plan
      run: terraform plan
      working-directory: ./terraform

    - name: Execute terraform apply 
      run: terraform apply -auto-approve
      working-directory: ./terraform

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        sudo mv trivy /usr/local/bin/

    - name: Verify Trivy Installation
      run: trivy --version

    - name: Run Trivy Config Scan
      run: trivy config .